import type { Metadata } from "next";
import { ReactNode } from "react";
import { Inter } from "next/font/google";
import "src/styles/globals.css";
import Header from "src/components/organisms/Header/Header";

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
